Sample code to work on some of the .h5 files; this should help you get an idea of what this dataset looks like, as well as what to add in a dataset of your own

In [7]:
import h5py
filename = "C:\\Users\\dylan\\Desktop\\ASCAD Dataset\\ASCAD_data\\ASCAD_databases\\ATMega8515_raw_traces.h5"

with h5py.File(filename, "r") as f:
    # Print all root level object names (aka keys) 
    # these can be group or dataset names 
    print("Keys: %s" % f.keys())
    # get first object name/key; may or may NOT be a group
    a_group_key = list(f.keys())[0]

    # get the object type for a_group_key: usually group or dataset
    print(type(f[a_group_key])) 

    # If a_group_key is a group name, 
    # this gets the object names in the group and returns as a list
    data = list(f[a_group_key])

    # If a_group_key is a dataset name, 
    # this gets the dataset values and returns as a list
    data = list(f[a_group_key])
    # preferred methods to get dataset values:
    ds_obj = f[a_group_key]      # returns as a h5py dataset object
    ds_arr = f[a_group_key][()]  # returns as a numpy array

Keys: <KeysViewHDF5 ['metadata', 'traces']>
<class 'h5py._hl.dataset.Dataset'>


In [4]:
data[0]

([  6,  65, 195,  66,  25, 182, 248,  19, 159, 132,  97,   6,  46, 137,  42,  16], [ 95,  75, 255, 146, 229,  35,  24,  50,  16, 107, 238,  33,  93,  56, 106, 178], [ 77, 251, 224, 242, 114,  33, 254,  16, 167, 141,  74, 220, 142,  73,   4, 105], [  7,  84,  71, 171, 129, 171,  90, 193, 236, 131,  21, 112, 185,  95, 212,  55])

In [16]:
ds_arr

array([([  6,  65, 195,  66,  25, 182, 248,  19, 159, 132,  97,   6,  46, 137,  42,  16], [ 95,  75, 255, 146, 229,  35,  24,  50,  16, 107, 238,  33,  93,  56, 106, 178], [ 77, 251, 224, 242, 114,  33, 254,  16, 167, 141,  74, 220, 142,  73,   4, 105], [  7,  84,  71, 171, 129, 171,  90, 193, 236, 131,  21, 112, 185,  95, 212,  55]),
       ([ 64,  84, 174, 122,  92, 107, 179,   4, 192,  55,  90, 128, 132,  74, 139,  27], [ 23, 248, 254,  14,  91, 201,   8, 132,  57, 212, 123,  91,  91, 233, 227,  72], [ 77, 251, 224, 242, 114,  33, 254,  16, 167, 141,  74, 220, 142,  73,   4, 105], [192, 166,  45,  89, 164,  22, 209, 144,   3, 192, 239, 152, 122,   7, 185,  67]),
       ([202, 207, 195,  33, 224, 159, 105,  75, 199,  25,   4,  96, 135, 145, 190, 130], [161, 211, 134, 179, 116, 181,  12, 169,  17, 225, 155,  57,  72,  40,   3, 164], [ 77, 251, 224, 242, 114,  33, 254,  16, 167, 141,  74, 220, 142,  73,   4, 105], [215, 205, 171,  53,  41, 211,  58, 129,  17, 194, 183, 240, 190,  48, 1

In [38]:
filename = "C:\\Users\\dylan\\Desktop\\ASCAD Dataset\\ASCAD_data\\ASCAD_databases\\ATMega8515_raw_traces.h5"

with h5py.File(filename, "r") as f:
    trace_0 = f['traces'][0]
    print(trace_0)
    print(f['metadata'][0]['plaintext'])
    print(f['metadata'][0]['ciphertext'])
    print(f['metadata'][0]['key'])
    print(f['metadata'][0]['masks'])
f.close()

[ 52  45  39 ... -18   2  21]
[  6  65 195  66  25 182 248  19 159 132  97   6  46 137  42  16]
[ 95  75 255 146 229  35  24  50  16 107 238  33  93  56 106 178]
[ 77 251 224 242 114  33 254  16 167 141  74 220 142  73   4 105]
[  7  84  71 171 129 171  90 193 236 131  21 112 185  95 212  55]


In [36]:
filename = "C:\\Users\\dylan\\Desktop\\ASCAD Dataset\\ASCAD_data\\ASCAD_databases\\ASCAD.h5"

with h5py.File(filename, "r") as f:
    trace_0 = f['Profiling_traces/traces'][0]
    print(trace_0, len(trace_0))
f.close()

[ 20  19  13   6  -2 -10 -19 -29 -39 -47 -52 -53 -52 -49 -45 -42 -38 -33
 -24 -13  -2   7  13  15  15  15  15  14  13  10   4  -4 -12 -20 -27 -33
 -39 -45 -48 -46 -39 -24 -10   3  10  11   8   4   3   6  11  16  18  17
  12   5  -3 -11 -21 -31 -40 -48 -51 -52 -50 -46 -42 -40 -38 -33 -26 -15
  -5   4  10  12  12  12  11  11   9   6  -1  -7 -15 -22 -28 -33 -38 -44
 -47 -46 -40 -29 -16  -4   2   4   1  -2  -3   1   5  10  11   9   5   0
  -7 -14 -21 -30 -38 -46 -50 -51 -49 -46 -43 -41 -39 -33 -26 -15  -6   3
   7   9   9   7   7   7   6   4  -2  -9 -17 -23 -29 -34 -39 -43 -46 -43
 -32 -16   5  24  35  38  33  28  22  22  24  27  29  26  20  10   0 -12
 -24 -37 -49 -59 -63 -63 -58 -51 -44 -39 -34 -29 -21 -11   1  12  20  25
  27  26  25  23  19  13   4  -5 -15 -24 -31 -38 -43 -48 -53 -54 -47 -35
 -19  -2  11  18  18  16  15  16  20  24  27  26  21  14   5  -5 -15 -27
 -37 -48 -56 -61 -60 -56 -52 -48 -43 -38 -31 -21 -10   0   8  13  15  16
  17  17  17  14   9   0  -9 -18 -25 -32 -38 -44 -4